### ISSUE TITLE
Code relys on that the compiler treats 'char' as 'signed char'

### ISSUE THREAD

**Issue by spachner** [fhunleth/code128#3]
Hi,

many thanks for this nice piece of code. Works fine. The only issue I found is that the code relys on that the compiler treats 'char' as 'signed char'. Otherwise your get a warning like

`warning: implicit conversion from 'int' to 'char' changes value from 255 to -1 [-Wconstant-conversion] 
`
in

```
static void code128_append_pattern(int pattern, int pattern_length, char *out)
{
    // All patterns have their first bit set by design
    assert(pattern & (1 << (pattern_length - 1)));

    int i;
    for (i = pattern_length - 1; i >= 0; i--)
        *out++ = (pattern & (1 << i)) ? 255 : 0;
}
```

and the assertion here traps:

```
static int code128_append_code(int code, char *p_out)
{
    assert(code >= 0 && code < (int) (sizeof(code128_pattern) / sizeof(code128_pattern[0])));
    code128_append_pattern(code128_pattern[code], CODE128_CHAR_LEN, p_out);
    return CODE128_CHAR_LEN;
}
```

regards

spachner

**Comment by fhunleth** [comment]
Hi! Thanks for letting me know about this.

This code is in a shipping product for me right now and I haven't been actively using it lately. Would you mind sending a PR with the changes that fix the warning. I'll merge them right in.

Thanks!!

**Comment by fhunleth** [comment]
Fixed in https://github.com/fhunleth/code128/commit/2444a7c9daa24d5a51083f23ea2f4ef44c69d89e.
